name: Deploy to Staging

on:
  push:
    paths:
      - 'staging/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl version --client

    - name: Apply staging resources
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl apply -f staging/
